receivers:
  otlp:
    protocols:
      grpc:
        
exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
processors:
  batch:
    
extensions:
  health_check:
  zpages:
    endpoint: :55679
    
service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [batch]